CREATE TABLE IF NOT EXISTS `datalist` (
  `id` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  `date` INT(11) NOT NULL
) ENGINE =InnoDB DEFAULT CHARSET=utf8;